// flow-typed signature: 27e9e571dbe845fc82c3865ddf916f52
// flow-typed version: <<STUB>>/redux-reqseq_v0.4.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-reqseq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-reqseq' {
  declare module.exports: any;
}
